name: FC_Rpg
main: me.Destro168.FC_Rpg.FC_Rpg
version: 0.82
description: Handles RPG aspects of the server.
commands:
   bighelp:
      description: This command displays all the help topics in /help at once.
   class:
      description: This command accesses donator commands.
   donator:
      description: This command accesses donator commands.
   dungeon:
      description: This command accesses dungeon commands.
   d9:
      description: This command accesses dungeon definition commands.
   faq:
      description: This command accesses server faq topics.
   g:
      description: This command toggles gamemode.
   h:
      description: This command RPG-heals a player.
   gh:
      description: This command performs /g and /h at once.
   hg:
      description: This command performs /g and /h at once.
   hat:
      description: This command puts your held block on your head.
   job:
      description: This command accesses job commands.
   list:
      description: This command displays online players.
   guild:
      description: This command accesses guild commands.
   pvp:
      description: This command accesses pvp commands.
   reset:
      description: This command resets an RPG players class.
   rpg:
      description: This command handles all admin commands.
   spell:
      description: This command accesses spell commands.
   modify:
      description: This command accesses modify commands.
   w:
      description: This command accesses warp commands.
   buff:
      description: This command accesses buff commands.
softdepend: [Multiverse, mcMMO]
depend: [FC_Suite_Shared]