name: FC_Rpg
main: me.Destro168.FC_Rpg.FC_Rpg
version: 1.34
description: Handles RPG aspects of the server.
commands:
   class:
      description: This command accesses donator commands.
   donator:
      description: This command accesses donator commands.
   dungeon:
      description: This command accesses dungeon commands.
   de:
      description: This command accesses dungeon extra commands.
   players:
      description: This command displays online players.
   faq:
      description: This command accesses server faq topics.
   g:
      description: This command toggles gamemode.
   h:
      description: This command RPG-heals a player.
   gh:
      description: This command performs /g and /h at once.
   hg:
      description: This command performs /g and /h at once.
   head:
      description: This command puts your held block on your head.
   job:
      description: This command accesses job commands.
   guild:
      description: This command accesses guild commands.
   pvp:
      description: This command accesses pvp commands.
   reset:
      description: This command resets an RPG players class.
   rpg:
      description: This command shows all commands available.
   rAdmin:
      description: This command handles all admin commands.
   spell:
      description: This command accesses spell commands.
   alchemy:
      description: This command accesses alchemy command.
   modify:
      description: This command accesses modify commands.
   w:
      description: This command accesses warp commands.
   buff:
      description: This command accesses buff commands.
   realm:
      description: This command accesses realm commands.
   forge:
      description: This command accesses forge commands.
   gold:
      description: This command accesses gold commands.
softdepend: [Multiverse, mcMMO, qQuests]
depend: [FC_Suite_Shared]